import { createContext, useContext, useState } from 'react';

const T = {
  en: {
    home:'Home',menu:'Menu',login:'Login',signup:'Sign Up',myOrders:'My Orders',logout:'Logout',
    heroTitle:'Taste the',heroAccent:'Extraordinary',
    heroSub:'Premium ingredients, masterfully crafted. Delivered to your doorstep in minutes.',
    orderNow:'Order Now →',
    fastDelivery:'Fast Delivery',fastDeliveryDesc:'Hot and fresh food delivered in 30 minutes or less.',
    masterChefs:'Master Chefs',masterChefsDesc:'Dishes crafted by award-winning chefs.',
    freshIngredients:'Fresh Ingredients',freshIngredientsDesc:'Only the finest, locally sourced organic ingredients.',
    readyToOrder:'Ready to Order?',exploreDishes:'Explore our wide range of delicious dishes',
    viewFullMenu:'View Full Menu →',popularDishes:'Popular Dishes',popularSub:'Our most loved meals',
    ourMenu:'Our',menuWord:'Menu',exploreMenu:'Explore our wide range of delicious dishes',
    addToCart:'+ Add to Cart',loading:'Loading menu...',
    yourCart:'Your Cart',cartEmpty:'Your cart is empty',addItems:'Add some delicious items from our menu',
    browseMenu:'Browse Menu',subtotal:'Subtotal',deliveryFee:'Delivery Fee',total:'Total',
    proceedToCheckout:'Proceed to Checkout →',clearCart:'Clear Cart',
    checkout:'CheckOut',shippingDetails:'1. SHIPPING DETAILS',
    streetAddress:'Street Address',city:'City',zipCode:'ZIP Code',
    paymentMethod:'2. PAYMENT METHOD',mobileMoneyLabel:'Mobile Money',
    cardLabel:'Card',cashLabel:'Cash',payNow:'Pay',backToCart:'← Back to Cart',
    welcomeBack:'Welcome Back',loginContinue:'Login to continue your food journey',
    email:'Email',password:'Password',forgotPassword:'Forgot password?',
    noAccount:"Don't have an account?",signIn:'Sign up',
    createAccount:'Create Account',joinUs:'Join us and enjoy great food',
    fullName:'Full Name',confirmPassword:'Confirm Password',
    repeatPassword:'Repeat password',alreadyAccount:'Already have an account?',
    myOrdersTitle:'My Orders',noOrders:'No orders yet',startOrdering:'Start ordering delicious food!',
    orderMore:'Order More 🍔',allOrders:'← All Orders',cancelOrder:'✕ Cancel Order',
    orderSummary:'Order Summary',itemsOrdered:'Items Ordered',
    deliveryAddress:'Delivery Address',paymentInfo:'Payment & Delivery',orderProgress:'Order Progress',
    pending:'Pending',confirmed:'Confirmed',preparing:'Preparing',
    outForDelivery:'Out for Delivery',delivered:'Delivered',cancelled:'Cancelled',
    premiumDesc:'Premium ingredients, masterfully crafted. Delivered to your doorstep in minutes.',
    quickLinks:'Quick Links',support:'Support',contactUs:'Contact Us',
    faq:'FAQ',privacyPolicy:'Privacy Policy',termsOfService:'Terms of Service',
    helpCenter:'Help Center',aboutUs:'About Us',contact:'Contact',
    dashboard:'Dashboard',orders:'Orders',menuItems:'Menu Items',users:'Users',
    totalRevenue:'Total Revenue',totalOrders:'Total Orders',pendingOrders:'Pending Orders',
    menuItemsLabel:'Menu Items',
    revenueTrend:'Revenue Trend',
    ordersPerDay:'Orders per Day',ordersPerMonth:'Orders per Month',
    ordersPerThreeMonths:'Orders per 3 Months',ordersPerSixMonths:'Orders per 6 Months',
    ordersPerYear:'Orders per Year',popularItems:'Popular Items',
    lastWeek:'Last Week',lastMonth:'Last Month',last3Months:'Last 3 Months',
    last6Months:'Last 6 Months',lastYear:'Last Year',
    orderManagement:'Order Management',menuManagement:'Menu Management',userManagement:'User Management',
    addItem:'+ Add Item',searchItems:'Search items...',searchUsers:'Search users...',
    newDish:'New Dish',dishName:'Dish Name',price:'Price ($)',category:'Category',
    description:'Description',dishImage:'Dish Image',saveChanges:'Save Changes',
    cancel:'Cancel',delete:'Delete',edit:'Edit',
    forgotPasswordTitle:'Forgot Password?',
    forgotPasswordSub:'Enter your email to get a reset code',
    sendResetCode:'Send Reset Code',resetPassword:'Reset Password',
    newPassword:'New Password',backToLogin:'← Back to Login',resetCodeLabel:'Reset Code',
    securePayment:'Secure Payment',fastDeliveryLabel:'Fast Delivery',
    freeCancellation:'Free cancellation within 5 mins',
    provider:'Provider',phoneNumber:'Phone Number',
    creditCardDetails:'Credit Card Details',cardNumber:'Card Number',
    cashNote:'Please have the exact amount ready upon delivery.',
    activeTab:'Action needed',activeDishes:'Active dishes',registered:'Registered',
  },
  so: {
    home:'Bogga',menu:'Cuntooyinka',login:'Gal',signup:'Diiwaan Geli',myOrders:'Dalabyadayda',logout:'Ka Bax',
    heroTitle:'Dhadhan',heroAccent:'Cajiib ah',
    heroSub:'Waaxyaabo tayo leh, oo si xirfad leh loo diyaariyey. Kuu gu yimaada gurigaaga daqiiqado gudahood.',
    orderNow:'Hadda Dalboo →',
    fastDelivery:'Dhiibitaan Degdeg ah',fastDeliveryDesc:'Cunto kulul oo hada lasameeyay kuhel 30 daqiiqo gudahood ama kayar.',
    masterChefs:'Jookhiyada Xirfadlayda',masterChefsDesc:'Cuntooyin ay diyaariyeen cunto-kariyayaal ku guuleystay abaalmarinno.',
    freshIngredients:'Waxyaabo Cusub',freshIngredientsDesc:'Waxaan isticmaalnaa oo keliya cunnooyinka dabiiciga ah ee ugu tayada sarreeya, kuwaas oo laga soo xulo deegaanka.',
    readyToOrder:'Diyaar ma u tahay?',exploreDishes:'Baar cuntooyinkayaga kala duwan',
    viewFullMenu:'Arag Cuntooyinka Oo Dhan →',popularDishes:'Cuntooyinka Caanka ah',popularSub:'Cuntooyinkayaga loogu jecel yahay',
    ourMenu:'Cuntoo-',menuWord:'yinkayaga',exploreMenu:'Baadh cuntooyinkeena kala duwan',
    addToCart:'+ Ku Dar',loading:'Cuntooyinka waa la guusoodhiibayaa...',
    yourCart:'Kooxdaada',cartEmpty:'Cuntooyinkaagu waa maran yihiin',addItems:'Ku dar cuntooyinka macaan',
    browseMenu:'Arag Cuntooyinka',subtotal:'Wadarta Hoose',deliveryFee:'Lacagta Keenista',total:'Wadarta',
    proceedToCheckout:'Bixi Lacagta →',clearCart:'Nadiifi Cuntooyinka aad dooratay',
    checkout:'Bixinta',shippingDetails:'1. CINWAANKA DHIIBISTA',
    streetAddress:'Cinwaanka Jidka',city:'Magaalada',zipCode:'Lambarka ZIP',
    paymentMethod:'2. HABKA LACAG BIXINTA',mobileMoneyLabel:'Lacagta Mobilka',
    cardLabel:'Kaarka',cashLabel:'Lacagta Caddaanka ah',payNow:'Bixi',backToCart:'← Ku Noqo Kooxda',
    welcomeBack:'Ku Soo Dhawoow',loginContinue:'Gal si aad u sii wadato',
    email:'Emailka',password:'Furaha Sirta',forgotPassword:'Ma illaawday furaha?',
    noAccount:'Ma lihid akoon?',signIn:'Diiwaan Geli',
    createAccount:'Samee Akoon',joinUs:'Nagu biir oo dhadhamso cuntada fiican',
    fullName:'Magaca Oo Dhan',confirmPassword:'Xaqiiji Furaha',
    repeatPassword:'Ku celi furaha',alreadyAccount:'Horay akoon u leedahay?',
    myOrdersTitle:'Dalabyadayda',noOrders:'Wali dalbo ma jiraan',startOrdering:'Bilow dalbasho cunto macaan!',
    orderMore:'Dalbo Mar Kale 🍔',allOrders:'← Dhammaan Dalbadayaasha',cancelOrder:'✕ Jooji Dalabka',
    orderSummary:'Koobka Dalabka',itemsOrdered:'Cuntooyinka La Dalbaday',
    deliveryAddress:'Cinwaanka Gaadhsiiska',paymentInfo:'Lacag Bixinta & Gaadhsiiska',orderProgress:'Horumarinta Dalabka',
    pending:'La Sugayo',confirmed:'La Xaqiijiyey',preparing:'La Diyaarinayaa',
    outForDelivery:'Jidka Ku Soojira',delivered:'La Geeyey',cancelled:'La Joojiyey',
    premiumDesc:'Waxyaalo tayo leh, si xirfad leh loo diyaariyey. Kuu gu yimaada daqiiqado gudahood.',
    quickLinks:'Xiriiriyeyaasha',support:'Taageero',contactUs:'Nala Xiriir',
    faq:"Su'aalaha",privacyPolicy:'Siyaasadda Gaarka',termsOfService:'Shuruudaha',
    helpCenter:'Xarunta Caawinta',aboutUs:'Naga',contact:'Xiriir',
    dashboard:'Xogta',orders:'Dalbadaha',menuItems:'Cuntooyinka',users:'Isticmaalayaasha',
    totalRevenue:'Dakhliga Guud',totalOrders:'Dalabaadka Guud',pendingOrders:'Dalabaadka La Sugayo',
    menuItemsLabel:'Cuntooyinka',
    revenueTrend:'Jihada Dakhliga',
    ordersPerDay:'Dalbashada Maalintii',ordersPerMonth:'Dalbashada Bishii',
    ordersPerThreeMonths:'Dalbashada 3 Bilood',ordersPerSixMonths:'Dalbashada 6 Bilood',
    ordersPerYear:'Dalbashada Sannadkii',popularItems:'Cuntooyinka Caanka ah',
    lastWeek:'Toddobaadkii',lastMonth:'Bishii',last3Months:'3 Bilood',
    last6Months:'6 Bilood',lastYear:'Sannadkii',
    orderManagement:'Maareynta Dalabaadka',menuManagement:'Maareynta Cuntooyinka',userManagement:'Maareynta Isticmaalayaasha',
    addItem:'+ Ku Dar',searchItems:'Baadh cuntooyinka...',searchUsers:'Baadh isticmaalayaasha...',
    newDish:'Cunto Cusub',dishName:'Magaca Cuntada',price:'Qiimaha ($)',category:'Nooca',
    description:'Sharaxaad',dishImage:'Sawirka Cuntada',saveChanges:'Kaydi Isbedelka',
    cancel:'Jooji',delete:'Tirtir',edit:'Wax ka Beddel',
    forgotPasswordTitle:'Ma Illaawday Furahaaga?',
    forgotPasswordSub:'Geli emailkaaga oo aan kuu dirno koodka',
    sendResetCode:'Dir Koodka',resetPassword:'Dib u Dejinta Furaha',
    newPassword:'Furaha Cusub',backToLogin:'← Ku Noqo Galitaanka',resetCodeLabel:'Koodka Dib u Dejinta',
    securePayment:'Lacag Bixin Ammaan',fastDeliveryLabel:'Gaadhsiis Degdeg',
    freeCancellation:'Joojin bilaash ah 5 daqiiqo gudahood',
    provider:'Bixiyaha',phoneNumber:'Lambarka Telefoonka',
    creditCardDetails:'Faahfaahinta Kaarka',cardNumber:'Lambarka Kaarka',
    cashNote:'Fadlan u diyaarso lacagta saxda ah marka dalabku kuu yimaado.',
    activeTab:'Jawaab looga baahan yahay',activeDishes:'Cuntooyin firfircoon',registered:'Diiwaan galiyey',
  }
};

const LangContext = createContext();
export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');
  const t = T[lang];
  const toggleLang = () => {
    const n = lang === 'en' ? 'so' : 'en';
    setLang(n);
    localStorage.setItem('lang', n);
  };
  return <LangContext.Provider value={{ lang, t, toggleLang }}>{children}</LangContext.Provider>;
};
export const useLang = () => useContext(LangContext);
